In [19]:
%cd /content

/content

In [20]:
from getpass import getpass

github_token = getpass("Enter your GitHub Token: ")
github_username = input("Enter your GitHub username: ")

Enter your GitHub Token: ··········
Enter your GitHub username: fleurclochette

In [21]:
!git clone https://{github_username}:{github_token}@github.com/fleurclochette/Scientific-Project-SS26.git /content/Scientific-Project-SS26

Cloning into '/content/Scientific-Project-SS26'...
remote: Enumerating objects: 193, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (184/184), done.
remote: Total 193 (delta 95), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (193/193), 385.33 KiB | 7.55 MiB/s, done.
Resolving deltas: 100% (95/95), done.

In [22]:
# Connect to repository
%cd /content/Scientific-Project-SS26

!git pull

/content/Scientific-Project-SS26
Already up to date.

In [23]:
# import libraries
import os   #use it mainly for handling file paths
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
# Define the GitHub repository directory
project_dir = "/content/Scientific-Project-SS26"

# Location of the raw dataset created in Notebook 01
raw_data_path = os.path.join(
    project_dir,
    "data",
    "raw",
    "sp500_raw.csv"
)

# Location where the processed dataset will be saved
processed_data_dir = os.path.join(
    project_dir,
    "data",
    "processed"
)

# Create processed folder if it does not exist
os.makedirs(
    processed_data_dir,
    exist_ok=True
)

# Full path for the processed dataset
processed_data_path = os.path.join(
    processed_data_dir,
    "processed_returns.csv"
)

In [25]:
# Check the raw dataset
print("Checking raw dataset location...")

print("Raw file path:")
print(raw_data_path)

print("\nFile exists:")
print(os.path.exists(raw_data_path))

Checking raw dataset location...
Raw file path:
/content/Scientific-Project-SS26/data/raw/sp500_raw.csv

File exists:
True

In [26]:
# Load the raw S&P 500 datasets
print("\nLoading raw S&P 500 dataset...")

df = pd.read_csv(
    raw_data_path,
    index_col=0,
    parse_dates=True
)

print("Dataset loaded successfully!")

print("\nFirst five observations:")
display(df.head())

Loading raw S&P 500 dataset...
Dataset loaded successfully!

First five observations:

                   Open         High          Low        Close      Volume
Date
2000-01-03  1469.250000  1478.000000  1438.359985  1455.219971   931800000
2000-01-04  1455.219971  1455.219971  1397.430054  1399.420044  1009000000
2000-01-05  1399.420044  1413.270020  1377.680054  1402.109985  1085500000
2000-01-06  1402.109985  1411.900024  1392.099976  1403.449951  1092300000
2000-01-07  1403.449951  1441.469971  1400.729980  1441.469971  1225200000

In [27]:
# Inspect the data
print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

Dataset information:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6684 entries, 2000-01-03 to 2026-07-31
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    6684 non-null   float64
 1   High    6684 non-null   float64
 2   Low     6684 non-null   float64
 3   Close   6684 non-null   float64
 4   Volume  6684 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 313.3 KB

Missing values:
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [28]:
# Missing Values
df = df.bfill()
df = df.ffill()

print("\nMissing values after filling:")
print(df.isnull().sum())

Missing values after filling:
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [29]:
# Calculating log returns
df["LogReturn"] = (
    np.log(
        df["Close"] / df["Close"].shift(1)
    )
) * 100
# The first observation has no previous closing price,
# so its log return is undefined and is removed.
df = df.dropna(
    subset=["LogReturn"]
)

In [30]:
# Save the processed dataset
df.to_csv(
    processed_data_path,
    index=False
)

print("\n" + "-" * 60)
print("Data processing completed successfully!")
print(
    f"Processed dataset saved to:\n"
    f"{processed_data_path}"
)
print("-" * 60)

------------------------------------------------------------
Data processing completed successfully!
Processed dataset saved to:
/content/Scientific-Project-SS26/data/processed/processed_returns.csv
------------------------------------------------------------

In [31]:
# Verification
print(f"\nTotal observations: {len(df)}")

display(df.head())

print("\nProcessed dataset information:")
df.info()

print(
    "\nProcessed file exists:",
    os.path.exists(processed_data_path)
)

Total observations: 6683

,Open,High,Low,Close,Volume,LogReturn
Date,,,,,,
2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1009000000,-3.909918
2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1085500000,0.192034
2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1092300000,0.095522
2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1225200000,2.672995
2000-01-10,1441.469971,1464.359985,1441.469971,1457.599976,1064800000,1.112782

Processed dataset information:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6683 entries, 2000-01-04 to 2026-07-31
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       6683 non-null   float64
 1   High       6683 non-null   float64
 2   Low        6683 non-null   float64
 3   Close      6683 non-null   float64
 4   Volume     6683 non-null   int64
 5   LogReturn  6683 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 365.5 KB

Processed file exists: True

In [33]:
%cd /content/Scientific-Project-SS26
!git status

/content/Scientific-Project-SS26
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/processed/processed_returns.csv

nothing added to commit but untracked files present (use "git add" to track)

In [34]:
!git add data/processed/processed_returns.csv

In [35]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   data/processed/processed_returns.csv

In [37]:
!git config --global user.name "fleurclochette"
!git config --global user.email "fleur.clochette.221@gmail.com"

In [38]:
!git commit -m "Add processed S&P 500 returns data"

[main ffcd513] Add processed S&P 500 returns data
 1 file changed, 6684 insertions(+)
 create mode 100644 data/processed/processed_returns.csv

In [43]:
!git commit -m "Merge remote changes with preprocessing updates"

[main 0f10964] Merge remote changes with preprocessing updates

In [44]:
!git push origin main

Enumerating objects: 13, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 2 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 190.70 KiB | 4.43 MiB/s, done.
Total 7 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 1 local object.
To https://github.com/fleurclochette/Scientific-Project-SS26.git
   926c8ea..0f10964  main -> main

In [45]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [46]:
!git commit -m "Merge remote changes with preprocessing updates"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean