In [ ]:
# Connect to repository
%cd /content/Scientific-Project-SS26

!git pull

In [ ]:
# To just check
import os

print(os.listdir("data/raw"))

In [ ]:
# import libraries
import os   #use it mainly for handling file paths
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Define the GitHub repository directory
project_dir = "/content/Scientific-Project-SS26"

# Location of the raw dataset created in Notebook 01
raw_data_path = os.path.join(
    project_dir,
    "data",
    "raw",
    "sp500_raw.csv"
)

# Location where the processed dataset will be saved
processed_data_dir = os.path.join(
    project_dir,
    "data",
    "processed"
)

# Create processed folder if it does not exist
os.makedirs(
    processed_data_dir,
    exist_ok=True
)

# Full path for the processed dataset
processed_data_path = os.path.join(
    processed_data_dir,
    "processed_returns.csv"
)

In [ ]:
# Check the raw dataset
print("Checking raw dataset location...")

print("Raw file path:")
print(raw_data_path)

print("\nFile exists:")
print(os.path.exists(raw_data_path))

In [ ]:
# Load the raw S&P 500 datasets
print("\nLoading raw S&P 500 dataset...")

df = pd.read_csv(
    raw_data_path,
    index_col=0,
    parse_dates=True
)

print("Dataset loaded successfully!")

print("\nFirst five observations:")
display(df.head())

In [ ]:
# Inspect the data
print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

In [ ]:
# Missing Values
df = df.bfill()
df = df.ffill()

print("\nMissing values after filling:")
print(df.isnull().sum())

In [ ]:
# Calculating log returns
df["LogReturn"] = (
    np.log(
        df["Close"] / df["Close"].shift(1)
    )
) * 100
# The first observation has no previous closing price,
# so its log return is undefined and is removed.
df = df.dropna(
    subset=["LogReturn"]
)

In [ ]:
# Save the processed dataset
df.to_csv(
    processed_data_path,
    index=False
)

print("\n" + "-" * 60)
print("Data processing completed successfully!")
print(
    f"Processed dataset saved to:\n"
    f"{processed_data_path}"
)
print("-" * 60)

Checking raw dataset location...
Raw file path:
/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/raw/sp500_raw.csv

File exists: True

Loading raw S&P 500 dataset...
Dataset loaded successfully!

First five observations:

                   Open         High          Low        Close      Volume
Date
2000-01-03  1469.250000  1478.000000  1438.359985  1455.219971   931800000
2000-01-04  1455.219971  1455.219971  1397.430054  1399.420044  1009000000
2000-01-05  1399.420044  1413.270020  1377.680054  1402.109985  1085500000
2000-01-06  1402.109985  1411.900024  1392.099976  1403.449951  1092300000
2000-01-07  1403.449951  1441.469971  1400.729980  1441.469971  1225200000

Dataset information:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6684 entries, 2000-01-03 to 2026-07-31
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    6684 non-null   float64
 1   High    6684 non-null   float64
 2   Low     6684 non-null   float64
 3   Close   6684 non-null   float64
 4   Volume  6684 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 313.3 KB

Missing values:
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

Missing values after filling:
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

------------------------------------------------------------
Data processing completed successfully!
Processed dataset saved to:
/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/processed/processed_returns.csv
------------------------------------------------------------

Total observations: 6683

,Open,High,Low,Close,Volume,LogReturn
Date,,,,,,
2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1009000000,-3.909918
2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1085500000,0.192034
2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1092300000,0.095522
2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1225200000,2.672995
2000-01-10,1441.469971,1464.359985,1441.469971,1457.599976,1064800000,1.112782

Processed dataset information:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6683 entries, 2000-01-04 to 2026-07-31
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       6683 non-null   float64
 1   High       6683 non-null   float64
 2   Low        6683 non-null   float64
 3   Close      6683 non-null   float64
 4   Volume     6683 non-null   int64
 5   LogReturn  6683 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 365.5 KB

In [ ]:
# Verification
print(f"\nTotal observations: {len(df)}")

display(df.head())

print("\nProcessed dataset information:")
df.info()

print(
    "\nProcessed file exists:",
    os.path.exists(processed_data_path)
)